"""adicionando_colunas

Revision ID: 2fee18462ff2
Revises: dd23b85674fa
Create Date: 2023-07-13 20:24:20.235019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fee18462ff2'
down_revision = 'dd23b85674fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ae', sa.Column('bi', sa.String(length=256), nullable=False))
    op.add_column('de', sa.Column('code', sa.String(length=256), nullable=False))
    op.add_column('ds', sa.Column('ml', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ds', 'ml')
    op.drop_column('de', 'code')
    op.drop_column('ae', 'bi')
    # ### end Alembic commands ###
