"""empty message

Revision ID: 528cac76f6f3
Revises: 70a5d8afb0cf
Create Date: 2023-07-14 15:02:09.603157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528cac76f6f3'
down_revision = '70a5d8afb0cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ae', 'bi',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ae', 'bi',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
