"""add_iaas_column

Revision ID: fe09730c4d8d
Revises: 2fee18462ff2
Create Date: 2023-07-13 20:30:50.500914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe09730c4d8d'
down_revision = '2fee18462ff2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('de', sa.Column('iaas', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('de', 'iaas')
    # ### end Alembic commands ###
